export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_LOGEDIN = 'TOGGLE_LOGEDIN';
export const TOGGLE_LOGIN_PAGE = 'TOGGLE_LOGIN_PAGE';
export const TOGGLE_EDITDC_PAGE = 'TOGGLE_EDITDC_PAGE';
export const TOGGLE_EDITREX_PAGE = 'TOGGLE_EDITREX_PAGE';
export const TOGGLE_EDITEXP_PAGE = 'TOGGLE_EDITEXP_PAGE';
export const TOGGLE_EDITPROFILE_PAGE = 'TOGGLE_EDITPROFILE_PAGE';